config/routes.rb
Tested::Application.routes.draw do
  devise_for :users

  root :to => "sessions#new"
  match '/new', to: "users#new"
  match '/signin',  to: "sessions#new"
  match '/signout',  to: "sessions#destroy", via: :delete
  get 'tags/:tag', to: 'photos#index', as: :tag
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users, :except => [:destroy] do
    resources :comments, :except => [:index]
    member do
        get :following, :followers
    end
    resources :photos do
      member { post :vote }
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	attr_accessible :posting, :private
	
	#validates :user_id, :pressence => true
	#validates :posting, :pressence => true, :length => { maximum: 200 }
	
	default_scope order: "comments.created_at DESC"
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_user
  before_filter :authenticate_user!
  
	def new
		@title = "New Comment"
		@comment = @user.comments.build
	end
  
	def create
		@comment = @user.comments.build(params[:comment])
		@comment.poster = current_user.id
		if @comment.save
			redirect_to user_url(@user), notice: "Comment posted"
		else
			render action: 'new'
		end
	end
  
	def edit
		@title = "Edit Comment"
		@comment = @user.comments.find(params[:id])
	end
  
	def update
		@title = "Update Photo"
		@comment = @user.comments.find(params[:id])
		if @comment.update_attributes(params[:comment])
			redirect_to user_comment_url(@user, @comment)
		else
			render action: 'edit'
		end
	end
  
	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		respond_to do |format|
			redirect_to user_url(@comment.user_id)
		end
  end
  
  private

	def load_user
		@user = User.find(params[:user_id])
	end
	
end

app/views/comments/edit.html.erb
<div class="container">
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>
</div>

app/views/comments/new.html.erb
<br />
<br />
<div class="container">
<h1>New comment</h1>
  <hr />
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for @comment, :url => user_comments_path(@user, @comment), :html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.text_area :posting %>
  </div>
  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', @user %>
</div>