config/routes.rb
Tested::Application.routes.draw do
  devise_for :users

  root :to => "sessions#new"
  match '/new', to: "users#new"
  match '/signin',  to: "sessions#new"
  match '/signout',  to: "sessions#destroy", via: :delete
  get 'tags/:tag', to: 'photos#index', as: :tag
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users, :except => [:destroy] do
    resources :comments, :except => [:index]
    member do
        get :following, :followers
    end
    resources :photos do
      member { post :vote }
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :private, :date_created, :email, :first_name, :last_login, :last_name, :username
  attr_accessor :delete_photo
  before_validation { photo.clear if delete_photo == '1' }
  has_secure_password
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token 
  has_many :evaluations, class_name: "RSEvaluation", as: :source
  has_reputation :votes, source: {reputation: :votes, of: :photos}, aggregated_by: :sum
  has_many :photos, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :pcomments, :dependent => :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :relationships, :dependent => :destroy, :foreign_key => "follower_id"
  has_many :reverse_relationships, :dependent => :destroy,
                                   :foreign_key => "followed_id",
                                   :class_name => "Relationship"
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships, :source  => :follower
  validates_presence_of :email, :first_name, :username, :last_name, :password, :on => :create
  has_attached_file :avatar, :styles => { :profileimg => "50x50>", :home => "150x150>" },
                    :url  => "/assets/photos/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/photos/:id/:style/:basename.:extension"
  validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 3.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  attr_protected :avatar_file_name, :avatar_content_type, :avatar_size
  validates :first_name,
                   :presence   => true,
                   :length     => {:in => 2..15},
                   :exclusion  => {:in => ['Admin', 'Root']}
  validates :last_name,
                   :presence   => true,
                   :length     => {:in => 2..15} ,
                   :exclusion  => {:in => ['Admin', 'Root']}
  VALID_USERNAME_REGEX = /\A\w+\Z/
  validates :username, :uniqueness => {:case_sensitive => false},
                   :presence   => true,
                   :length     => {:in => 3..15},
                   :exclusion  => {:in => ['Admin', 'Root']},
                   format: {with: VALID_USERNAME_REGEX}
  validates :password,
                   :presence   => true,
                   :length     => {:in => 5..15},
                   :confirmation => true
  validates_confirmation_of :password 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :uniqueness => {:case_sensitive => false},
                   :presence   => true,
                   :length     => {:in => 5..45},
                   format: { with: VALID_EMAIL_REGEX }

  def to_s
    username
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def self.find_by_id(id)
    find(:id) rescue nil
  end

  def voted_for?(photo)
    evaluations.where(target_type: photo.class, target_id: photo.id).present?
  end

  def self.search(search)
      if search
        find(:all, :conditions => ['username LIKE ?', "%#{search}%"])
      else
        find(:all)
      end
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :authenticate_user!
  
	def show
		@title = "Profile"
		@user = User.find(params[:id])	
	end

	def index
		@title ="All Users"
		@users = User.all
		@users = User.search(params[:search])
	end
	
	def new
		@title = "New User"
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@title ="Edit User"
		@user = User.find(params[:id])
	end

	def update
		@title = "User Settings"
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to @user, notice: 'User was successfully updated.' 
		else
			render action: "edit"
		end
	end

	def following
    	@title = "Following"
    	@user = User.find(params[:id])
    	@users = @user.following.paginate(page: params[:page])
    	render 'show_follow'
  	end

  	def followers
    	@title = "Followers"
    	@user = User.find(params[:id])
    	@users = @user.followers.paginate(page: params[:page])
    	render 'show_follow'
  	end

  private

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url, notice: "Please sign in."
		end
	end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(:followed_id => @user.id), :remote => true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div><%= f.submit "Follow", method: "post" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete }, :remote => true) do |f| %>
  <div><%= f.submit "Unfollow", method: "post" %></div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to image_tag(user.avatar.url(:profileimg)), user %>
  <%= link_to user.username, user %>
</li>

app/views/users/edit.html.erb
<br />
<br />
<br />
<div class="container">
<h1> Edit User </h1>
<hr />
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @user, :html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, :required => true %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, :required => true %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :required => true %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :required => true %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation, :required => true %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br /> 
    <%= image_tag @user.avatar.url(:profileimg) %><br />
    <br />
    <%= f.label :new_avatar %>
    Choose a new avatar: <%= f.file_field :avatar %>
  </div><br />
  <div class="field">
    <%= f.label :make_profile_private? %>
    <%= f.check_box :private %>
  </div><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', @user %>
</div>

app/views/users/index.html.erb
<br />
<br />
<div class="container result"> 
  <div class="one-third column">
      <h2>Filter Users: </h2>
      <hr />
      <%= form_tag users_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :username => nil %>
        <% if params[:search] %>
           <%= link_to "Clear Filter", users_path %>
        <% end %>
      <% end %>
    </div>
  <div class="two-thirds column">
    <h2>Users: </h2> 
      <hr />
      <ul>
        <% @users.each do |user|  %>
          <% if !current_user?(user) %>
            <li>
              <%= image_tag user.avatar.url(:profileimg) %>
              <%= link_to user.username, user %>
            </li>
          <% end %>
        <% end %>
      </uL>
    </div>
</div>

app/views/users/new.html.erb
<br />
<div class="container">
<h1> New User </h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, :required => true %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, :required => true %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, :required => true %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :required => true %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation, :required => true %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :required => true %>
  </div>
  <div class="field">
    Choose an avatar<%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', root_path %>
</div>

app/views/users/show.html.erb
<br />
<br />
<div class="container result">
<center><h2><%= @user.username %></h2>
	<%= link_to image_tag(@user.avatar.url(:home)) %><br /></center>
	<hr />
	<% if @user.private == false || current_user?(@user) %>
<div class="one-third column">
	<h3>Photo Uploads:</h3>
	<% if current_user?(@user) %>
	<%= button_to "New Photo Upload", new_user_photo_path(current_user), method: "get" %>
	<% end %>
	<ul>
		<% @user.photos.each do |photo| %>
			<% if photo.private == false || current_user?(@user) %>
				<%= image_tag photo.photo.url(:thumb) %>
				<li>
					<%= photo.title %> | <%= link_to 'Show', user_photo_path(@user, photo) %> 
				</li>
			<% end %>
		<% end %>	
	</ul>	
</div>	
<div class="one-third column">
	<h3>Comments:</h3>
	<%= button_to "Post Comment", new_user_comment_path(@user), method: "get" %>
	<br /><br />
	<ul>
		<% @user.comments.each do |comment| %>
			<% @poster = User.find(comment[:poster]) %>
			<% if (comment.private == false || current_user?(@user) || current_user?(@poster)) %>
				<li> 
					<%= link_to image_tag @poster.avatar.url(:profileimg) %>
					<%= link_to @poster.username, @poster %>
				</li>
				<li> 
					<em>Posted <%= time_ago_in_words(comment.created_at) %> ago </em>
				</li>
				<li> 
					<%= comment.posting %> 
				</li>
				<br />
			<% end %>
		<% end %>
	</ul>
</div>
<div class="one-third column">
	<h3>Friends:</h3>
	<%= render 'follow_form' if signed_in? %>
	<%= render 'shared/stats' %>
</div>
<% else %>
<br /><br />
<strong>This profile is set to private</strong>
<% end %>

app/views/users/show_follow.html.erb
<br />
<br />
<div class="container result">
  <div class="two-thirds column">
      <h1><%= @title %>:</h1>
      <% if @users.any? %>
        <ul>
          <%= render @users %>
        </ul>  
        <%= will_paginate @users %>
      <% end %>
  </div>
  <div class="one-third column">
      <strong>Name</strong> <%= @user.username %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <% @users.each do |user| %>
          <%= link_to image_tag(user.avatar.url(:profileimg)), user %>
        <% end %>
      <% end %>
  </div>
</div>