config/routes.rb
Tested::Application.routes.draw do
  devise_for :users

  root :to => "sessions#new"
  match '/new', to: "users#new"
  match '/signin',  to: "sessions#new"
  match '/signout',  to: "sessions#destroy", via: :delete
  get 'tags/:tag', to: 'photos#index', as: :tag
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users, :except => [:destroy] do
    resources :comments, :except => [:index]
    member do
        get :following, :followers
    end
    resources :photos do
      member { post :vote }
    end
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :photo, :tag_list, :date_uploaded, :description, :last_view, :num_comments, :private, :rating, :title, :view_count
  validates_presence_of :title
  acts_as_taggable
  has_many :pcomments
  has_reputation :votes, source: :user, aggregated_by: :sum
  has_attached_file :photo, :styles => {:edit => "550x550>", :small => "300x300>", :thumb => "150x150>" },
                    :url  => "/assets/photos/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/photos/:id/:style/:basename.:extension"
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 10.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png', 'image/gif']
  attr_protected :photo_file_name, :photo_content_type, :photo_size
  validates :title,
                   :presence   => true,
                   :length     => {:in => 2..25} 
                   
  def delete_photo=(value)
    @delete_photo = !value.to_i.zero?
  end

  def delete_photo
    !!@delete_photo
  end
  alias_method :delete_photo?, :delete_photo

  before_validation :clear_photo
  def clear_photo
    self.photo = nil if delete_photo? && !photo.dirty?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_filter :authenticate_user!
	
  	def index
  		if params[:tag]
  			@photos = Photo.tagged_with(params[:tag])
  		else
  			@photos = Photo.all
  		end
  	end

  	def vote
  		value = params[:type] == "up" ? 1 : -1
  		@photo = Photo.find(params[:id])
  		@photo.add_or_update_evaluation(:votes, value, current_user)
  		redirect_to :back, notice: "Thank you for voting"
	end

	def show
		@title = "View Image"
		@photo = Photo.find(params[:id])
		@user = User.find(params[:user_id])
		@photos = Photo.find_with_reputation(:votes, :all, order: "votes desc")
	end

	def new
		@title = "Upload a Picture"
		@user = User.find(params[:user_id])
		@photo = @user.photos.build
	end

	def edit
		@title = "Edit Photo"
		@user = User.find(params[:user_id])
		@photo = @user.photos.find(params[:id])
	end

	def create 
		@user = User.find(params[:user_id])
		@photo = @user.photos.build(params[:photo])
		if @photo.save
			redirect_to user_url(@user), notice: 'Photo was successfully created.'
		else
			render action: "new"
		end
	end

	def update
		@title = "Edit Photo"
		@user = User.find(params[:user_id])
		@photo = @user.photos.find(params[:id])
		if @photo.update_attributes(params[:photo])
			redirect_to user_photo_url(@user, @photo), notice: 'Photo was successfully updated.'
		else
			render action: "edit"
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		@photo = @user.photos.find(params[:id])
		@photo.destroy
		respond_to do |format|
			redirect_to user_url(@user), notice: 'Deleted photo'
		end
	end
 end

app/views/photos/edit.html.erb
<br />
<br />
<br />
<div class="container">
  <h1>Editing photo</h1>
  <hr />
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="one-third column">
    <%= form_for @photo, :url => user_photo_path(@user, @photo), :html => { :multipart => true } do |f| %>
      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title, :required => true %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= f.label :tag_list, "Tags (separated by commas)" %><br />
        <%= f.text_field :tag_list %>
      </div>
      <div class="field">
        <%= f.label :make_photo_private? %>
        <%= f.check_box :private %>
      </div><br />
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
    <%= link_to 'Back', @user %>
  </div>
 
  <div class="two-thirds column">
    <%= form_for @photo, :url => user_photo_path(@user, @photo), :html => { :multipart => true } do |f| %>
      <p>
        <%= image_tag @photo.photo.url(:edit) %>
      <p>
    <% end %>
  </div> 
  
</div>

app/views/photos/index.html.erb
<br />
<br />
<div class="container result">
	<div class="two-thirds column">
		<h1>Photos tagged with <%= params[:tag] %>:</h2>
		<hr />
		<ul>
			<% @photos.each do |photo| %>
				<% if !photo.private %>
				<h2><%= photo.title %></h2>
		 		<%= link_to image_tag(photo.photo.url(:thumb)), photo.photo.url %><br />
				Username: <%= link_to photo.user, photo.user %><br />
     			Photo tags:<br /> <%= raw photo.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
  			<% end %>
  			<% end %>
		</ul>
	</div>
<div class="one-third column">
	<h1> Tag Cloud: </h1>
	<hr />
 	<% tag_cloud Photo.tag_counts, %w[s m l] do |tag, css_class| %>
    	<%= link_to tag.name, tag_path(tag.name), class: css_class %>
  	<% end %>
	</div>
</div>

app/views/photos/new.html.erb
<br />
<br />
<div class="container">
<h1>New photo</h1>
  <hr />
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for @photo, :url => user_photos_path(@user, @photo), :html => { :multipart => true } do |f| %>
  <div class="field">   
    <%= f.file_field :photo, :required => true%>
    (10 MEGS or smaller please)
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :required => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', @user %>
</div>

app/views/photos/show.html.erb
<br />
<br />
<div class="container result">
<center><h1><%= @photo.title %> </h1>
<%= link_to image_tag @photo.photo.url %><br />
<b>Description:</b><br />
<%= @photo.description %><br />
  <br />
  <b>Votes:</b> <%= @photo.reputation_for(:votes).to_i %><br />
	<% if current_user && !current_user.voted_for?(@photo) %>
  <%= link_to "up", vote_user_photo_path(@user, @photo, type: "up"), method: "post" %>
  | <%= link_to "down", vote_user_photo_path(@user, @photo, type: "down"), method: "post" %>
<% end %><br /><br />
<b>Tags:</b><br />
  <%= raw @photo.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
  <br />
  <br />
  <br />
<%= link_to 'Back', @user %> 
<% if current_user?(@user) %>
| <%= link_to 'Edit', edit_user_photo_path(@user, @photo) %></center>
<% end %>
</div>