config/routes.rb
Tested::Application.routes.draw do
  devise_for :users

  root :to => "sessions#new"
  match '/new', to: "users#new"
  match '/signin',  to: "sessions#new"
  match '/signout',  to: "sessions#destroy", via: :delete
  get 'tags/:tag', to: 'photos#index', as: :tag
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users, :except => [:destroy] do
    resources :comments, :except => [:index]
    member do
        get :following, :followers
    end
    resources :photos do
      member { post :vote }
    end
  end
end

app/views/layouts/_header.html.erb
<div class="container">
  <header>
    <nav class="round">
      <div id="nav">
        <ul>
          <% if signed_in? %>
            <li><%= link_to image_tag("camera-header.png"), "/signin" %></li>
            <li><%= link_to "USERS", users_path %></li>
            <li><%= link_to "PROFILE", user_path(current_user) %></li>
            <li><%= link_to "SETTINGS", edit_user_path(current_user) %></li>
            <li><%= link_to "SIGN OUT", signout_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= favicon_link_tag "icon.png" %>
  <%= stylesheet_link_tag    "base", :media => "all" %>
  <%= stylesheet_link_tag    "layout", :media => "all" %>
  <%= stylesheet_link_tag    "skeleton", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>
</body>
</html>